icc: part2_A.c part2_B.c part2_C.c sudoku_solver.c sudoku_solver_optimized.c 
	icc part2_A.c -o part2_A -qopenmp -lm
	icc part2_B.c -o part2_B -qopenmp -lm
	icc part2_C.c -o part2_C -qopenmp -lm
	icc sudoku_solver.c -o sudoku_solver -qopenmp -lm
	icc sudoku_solver_optimized.c -o sudoku_solver_optimized -qopenmp -lm
	
