# icc: sudoku_solver.c
# 	icc sudoku_solver.c -o sudoku_solver -qopenmp -lm

# gcc: sudoku_solver.c
# 	gcc -o sudoku_solver sudoku_solver.c -fopenmp -lm

icc: task2.c
	icc task2.c -o task2 -qopenmp -lm

gcc: task2.c
	gcc -o task2 task2.c -fopenmp -lm
